# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hashtagging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hashtagging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hashtagging.proto\x12\x0bhashtagging\"&\n\x0eHashtagRequest\x12\x14\n\x0cpost_content\x18\x01 \x01(\t\"\"\n\x0fHashtagResponse\x12\x0f\n\x07hashtag\x18\x01 \x01(\t2Y\n\x0eHashtagService\x12G\n\nGetHashtag\x12\x1b.hashtagging.HashtagRequest\x1a\x1c.hashtagging.HashtagResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hashtagging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASHTAGREQUEST']._serialized_start=34
  _globals['_HASHTAGREQUEST']._serialized_end=72
  _globals['_HASHTAGRESPONSE']._serialized_start=74
  _globals['_HASHTAGRESPONSE']._serialized_end=108
  _globals['_HASHTAGSERVICE']._serialized_start=110
  _globals['_HASHTAGSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
